### ISSUE TITLE
can i know what def config to use for mi a2 in unified branch?

### ISSUE THREAD

**Issue by beakthoven** [SiddharthBharadwaj/android_kernel_xiaomi_jasmine_sprout#1]
can I know what def config to use for mi a2 in unified branch to compile the kernel, and I want to know what toolchain you have used to compile it.

thank you

**Comment by SiddharthBharadwaj** [comment]
wayne_defconfig using Proton clang

**Comment by beakthoven** [comment]
Thank you sir, it would be great if you renamed it to device-name_defconfig ie Jasmin sprout_defconfig as it would be easy for Devs to find out the right one.
